# Generated by Django 3.0.8 on 2020-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.TextField(default='CSSE', verbose_name=10),
            preserve_default=False,
        ),
    ]
