# Generated by Django 3.0.8 on 2020-07-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_post_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.CharField(max_length=10),
        ),
    ]
