# Generated by Django 3.0.8 on 2020-07-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20200707_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
    ]
